--
-- PK_APPR_LINE  (Index) 
--
CREATE UNIQUE INDEX PK_APPR_LINE ON APPR_LINE
(APPR_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_APPR_LINE1  (Index) 
--
CREATE UNIQUE INDEX PK_APPR_LINE1 ON APPR_LINE
(APPR_SEQ, APPR_MST_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_APPR_DEPT_DTL  (Index) 
--
CREATE UNIQUE INDEX PK_APPR_DEPT_DTL ON APPR_DEPT_DTL
(APPR_DTL_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- KOLAS_ADD_FILE_PK  (Index) 
--
CREATE UNIQUE INDEX KOLAS_ADD_FILE_PK ON KOLAS_ADD_FILE
(FILE_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_APPR_DEPT_MST  (Index) 
--
CREATE UNIQUE INDEX PK_APPR_DEPT_MST ON APPR_DEPT_MST
(APPR_MST_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- MTLR_REQ_PK  (Index) 
--
CREATE UNIQUE INDEX MTLR_REQ_PK ON MTLR_REQ
(MTLR_MST_NO, MTLR_REQ_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_COMMON_CODE  (Index) 
--
CREATE UNIQUE INDEX PK_COMMON_CODE ON COMMON_CODE
(CODE)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ESTIMATE_FEE_GUBUN_PK  (Index) 
--
CREATE UNIQUE INDEX ESTIMATE_FEE_GUBUN_PK ON ESTIMATE_FEE_GUBUN
(EST_FEE_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_COMMON_CODE_DETAIL  (Index) 
--
CREATE UNIQUE INDEX PK_COMMON_CODE_DETAIL ON COMMON_CODE_DETAIL
(CODE)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- KOLAS_DOC_PK  (Index) 
--
CREATE UNIQUE INDEX KOLAS_DOC_PK ON KOLAS_DOC
(KOLAS_DOC_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_DEPART  (Index) 
--
CREATE UNIQUE INDEX PK_DEPART ON DEPART
(DEPT_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- CMMN_SPEC_KIND_LOG_PK  (Index) 
--
CREATE UNIQUE INDEX CMMN_SPEC_KIND_LOG_PK ON CMMN_SPEC_KIND_LOG
(CMMN_SPEC_CD, LAST_UPDT_DTM)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- CMMN_SPEC_PK  (Index) 
--
CREATE UNIQUE INDEX CMMN_SPEC_PK ON CMMN_SPEC
(CMMN_SPEC_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- CMMN_SPEC_LOG_PK  (Index) 
--
CREATE UNIQUE INDEX CMMN_SPEC_LOG_PK ON CMMN_SPEC_LOG
(CMMN_SPEC_SEQ, LAST_UPDT_DTM)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ACCOUNT_PK  (Index) 
--
CREATE UNIQUE INDEX ACCOUNT_PK ON ACCOUNT
(ACCOUNT_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- CMMN_SPEC_KIND_PK  (Index) 
--
CREATE UNIQUE INDEX CMMN_SPEC_KIND_PK ON CMMN_SPEC_KIND
(CMMN_SPEC_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ACCESS_IP_MANAGE_PK  (Index) 
--
CREATE UNIQUE INDEX ACCESS_IP_MANAGE_PK ON ACCESS_IP_MANAGE
(IP_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ACCOUNT_APPLY_PK  (Index) 
--
CREATE UNIQUE INDEX ACCOUNT_APPLY_PK ON ACCOUNT_APPLY
(TEST_SAMPLE_SEQ, TEST_ITEM_CD, ACCOUNT_NO, ACCOUNT_DETAIL_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ACCOUNT_DETAIL_PK  (Index) 
--
CREATE UNIQUE INDEX ACCOUNT_DETAIL_PK ON ACCOUNT_DETAIL
(ACCOUNT_NO, ACCOUNT_DETAIL_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ADDR  (Index) 
--
CREATE INDEX ADDR ON ZIP_ADDR_OLD
(SIDO, DONG, JI_BON_NUM, GUN_BON_NUM, DORO_NM)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          636M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ANALYSIS_LOG_PK  (Index) 
--
CREATE UNIQUE INDEX ANALYSIS_LOG_PK ON ANALYSIS_LOG
(TESTITM_CD, LAST_UPDT_DTM)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ANALYSIS_PK  (Index) 
--
CREATE UNIQUE INDEX ANALYSIS_PK ON ANALYSIS
(TESTITM_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- AUDIT_TRAIL_PK  (Index) 
--
CREATE UNIQUE INDEX AUDIT_TRAIL_PK ON AUDIT_TRAIL
(AT_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- BOARD_PK  (Index) 
--
CREATE UNIQUE INDEX BOARD_PK ON BOARD
(BOARD_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- CMMN_EXPT_PRDLST_LOG_PK  (Index) 
--
CREATE UNIQUE INDEX CMMN_EXPT_PRDLST_LOG_PK ON CMMN_SPEC_KIND_EXPT_PRDLST_LOG
(CMMN_SPEC_CD, PRDLST_CD, TESTITM_CD, LAST_UPDT_DTM)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ABSENCE_PK  (Index) 
--
CREATE UNIQUE INDEX ABSENCE_PK ON ABSENCE
(USER_ID)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_INST_RPR_HIS  (Index) 
--
CREATE UNIQUE INDEX PK_INST_RPR_HIS ON INST_RPR_HIS
(RPR_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- CMMN_SPEC_KIND_EXPT_PRDLST_PK  (Index) 
--
CREATE UNIQUE INDEX CMMN_SPEC_KIND_EXPT_PRDLST_PK ON CMMN_SPEC_KIND_EXPT_PRDLST
(CMMN_SPEC_CD, PRDLST_CD, TESTITM_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_ROLE_GROUP_MENU  (Index) 
--
CREATE UNIQUE INDEX PK_ROLE_GROUP_MENU ON ROLE_GROUP_MENU
(ROLE_NO, MENU_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_ROLE_GROUP  (Index) 
--
CREATE UNIQUE INDEX PK_ROLE_GROUP ON ROLE_GROUP
(ROLE_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_INST_CRT_HIS  (Index) 
--
CREATE UNIQUE INDEX PK_INST_CRT_HIS ON INST_CRT_HIS
(CRT_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_EDU_RESULT  (Index) 
--
CREATE UNIQUE INDEX PK_EDU_RESULT ON EDU_RESULT
(EDU_RESULT_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_EDU_ATTEND  (Index) 
--
CREATE UNIQUE INDEX PK_EDU_ATTEND ON EDU_ATTEND
(ATTEND_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_DEPT_USER_ITEM  (Index) 
--
CREATE UNIQUE INDEX PK_DEPT_USER_ITEM ON DEPT_USER_ITEM
(DEPT_USER_ITEM_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_FEE_GROUP  (Index) 
--
CREATE UNIQUE INDEX PK_FEE_GROUP ON FEE_GROUP
(FEE_GROUP_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_INST_RPR_HIS1  (Index) 
--
CREATE UNIQUE INDEX PK_INST_RPR_HIS1 ON INST_RPR_HIS
(RPR_NO, INST_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_TEST_REQ  (Index) 
--
CREATE UNIQUE INDEX PK_TEST_REQ ON TEST_REQ
(TEST_REQ_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_TEST_METHOD  (Index) 
--
CREATE UNIQUE INDEX PK_TEST_METHOD ON TEST_METHOD
(TEST_METHOD_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_TEST_ITEM_GROUP  (Index) 
--
CREATE UNIQUE INDEX PK_TEST_ITEM_GROUP ON TEST_ITEM_GROUP
(TEST_ITEM_GROUP_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PRDLST_CL_PK  (Index) 
--
CREATE UNIQUE INDEX PRDLST_CL_PK ON PRDLST_CL
(PRDLST_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PRDLST_CL_LOG_PK  (Index) 
--
CREATE UNIQUE INDEX PRDLST_CL_LOG_PK ON PRDLST_CL_LOG
(PRDLST_CD, LAST_UPDT_DTM)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- FK_APPR_DEPT_DTL  (Index) 
--
CREATE INDEX FK_APPR_DEPT_DTL ON APPR_DEPT_DTL
(APPR_MST_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ESTIMATE_PK  (Index) 
--
CREATE UNIQUE INDEX ESTIMATE_PK ON ESTIMATE
(EST_NO, EST_ORG_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ESTIMATE_ITEM_FEE_PK  (Index) 
--
CREATE UNIQUE INDEX ESTIMATE_ITEM_FEE_PK ON ESTIMATE_ITEM_FEE
(EST_NO, EST_FEE_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- REPORT_SAMPLE_PK  (Index) 
--
CREATE UNIQUE INDEX REPORT_SAMPLE_PK ON REPORT_SAMPLE
(REPORT_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- INST_MNG_HIS_PK  (Index) 
--
CREATE UNIQUE INDEX INST_MNG_HIS_PK ON INST_MNG_HIS
(INST_NO, MNG_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ZIP_ADDR_INDEX1  (Index) 
--
CREATE INDEX ZIP_ADDR_INDEX1 ON ZIP_ADDR
("SIDO" DESC, "SIGUN" DESC)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- SEARCH_ADD  (Index) 
--
CREATE INDEX SEARCH_ADD ON ZIP_ADDR_OLD
(HANGJUNG_DONG)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          239M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- SAMPLE_TEMP_ITEM_PK  (Index) 
--
CREATE UNIQUE INDEX SAMPLE_TEMP_ITEM_PK ON SAMPLE_TEMP_ITEM
(SAMPLE_TEMP_CD, TEMP_SEQ, TEST_ITEM_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- TEST_SAMPLE_ITEM_HISTORY_PK  (Index) 
--
CREATE UNIQUE INDEX TEST_SAMPLE_ITEM_HISTORY_PK ON TEST_SAMPLE_ITEM_HISTORY
(ITEM_HIS_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_SAMPLE  (Index) 
--
CREATE UNIQUE INDEX PK_SAMPLE ON SAMPLE
(SAMPLE_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_ROLE_GROUP_USER  (Index) 
--
CREATE UNIQUE INDEX PK_ROLE_GROUP_USER ON ROLE_GROUP_USER
(ROLE_NO, USER_ID)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- HAENGJEONG_NM  (Index) 
--
CREATE INDEX HAENGJEONG_NM ON ZIP_ADDR
(HAENGJEONG_NM)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- FORM_PK  (Index) 
--
CREATE UNIQUE INDEX FORM_PK ON FORM
(FORM_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- STD_TEST_ITEM_PK  (Index) 
--
CREATE UNIQUE INDEX STD_TEST_ITEM_PK ON BAK_STD_TEST_ITEM
(TEST_ITEM_CD, TEST_STD_NO, REV_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- SIGUN_BUILDING_NM  (Index) 
--
CREATE INDEX SIGUN_BUILDING_NM ON ZIP_ADDR
(SIGUN_BUILDING_NM)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_REQ_ORG  (Index) 
--
CREATE UNIQUE INDEX PK_REQ_ORG ON REQ_ORG
(REQ_ORG_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- INDV_SPEC_LOG_PK  (Index) 
--
CREATE UNIQUE INDEX INDV_SPEC_LOG_PK ON INDV_SPEC_LOG
(INDV_SPEC_SEQ, LAST_UPDT_DTM)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_MENU  (Index) 
--
CREATE UNIQUE INDEX PK_MENU ON MENU
(MENU_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_KEY  (Index) 
--
CREATE UNIQUE INDEX PK_KEY ON COUNSEL_PERSONAL
(TOTAL_NO, PERSONAL_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- TEST_ITEM_GROUP_ITEM_PK  (Index) 
--
CREATE UNIQUE INDEX TEST_ITEM_GROUP_ITEM_PK ON TEST_ITEM_GROUP_ITEM
(TEST_ITEM_GROUP_NO, DEPT_CD, TEST_ITEM_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- INDV_SPEC_PK  (Index) 
--
CREATE UNIQUE INDEX INDV_SPEC_PK ON INDV_SPEC
(INDV_SPEC_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- REPORT_NAME_PK  (Index) 
--
CREATE UNIQUE INDEX REPORT_NAME_PK ON REPORT_NAME
(REPORT_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- TEST_REPORT_ATTACH_PK  (Index) 
--
CREATE UNIQUE INDEX TEST_REPORT_ATTACH_PK ON TEST_REPORT_ATTACH
(ATT_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- TEST_REPORT_PK  (Index) 
--
CREATE UNIQUE INDEX TEST_REPORT_PK ON TEST_REPORT
(TEST_SAMPLE_SEQ, TEST_ITEM_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- TEST_ITEM_METHOD_PK  (Index) 
--
CREATE UNIQUE INDEX TEST_ITEM_METHOD_PK ON TEST_ITEM_METHOD
(TEST_ITEM_CD, TEST_METHOD_NO, TEST_STD_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- TEST_ITEM_INST_PK  (Index) 
--
CREATE UNIQUE INDEX TEST_ITEM_INST_PK ON TEST_ITEM_INST
(TEST_ITEM_CD, INST_NO, TEST_STD_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- TEST_ITEM_ATTACH_PK  (Index) 
--
CREATE UNIQUE INDEX TEST_ITEM_ATTACH_PK ON TEST_SAMPLE_ITEM_ATTACH
(ATT_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_TEST_ITEM  (Index) 
--
CREATE UNIQUE INDEX PK_TEST_ITEM ON TEST_ITEM
(TEST_ITEM_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_TEST_COMMENT  (Index) 
--
CREATE UNIQUE INDEX PK_TEST_COMMENT ON TEST_COMMENT
(TEST_REQ_NO, TESTER_ID)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_SAMPLING_POINT  (Index) 
--
CREATE UNIQUE INDEX PK_SAMPLING_POINT ON SAMPLING_POINT
(SAMPLING_POINT_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_PROCESS  (Index) 
--
CREATE UNIQUE INDEX PK_PROCESS ON PROCESS
(PRC_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- TEST_SAMPLE_DISUSE_PK  (Index) 
--
CREATE UNIQUE INDEX TEST_SAMPLE_DISUSE_PK ON TEST_SAMPLE_DISUSE
(TEST_SAMPLE_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_SAMPLE_TEMP  (Index) 
--
CREATE UNIQUE INDEX PK_SAMPLE_TEMP ON SAMPLE_TEMP
(SAMPLE_TEMP_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_SAMPLE_TEMP_ITEM  (Index) 
--
CREATE UNIQUE INDEX PK_SAMPLE_TEMP_ITEM ON SAMPLE_TEMP_ITEM
(TEMP_SEQ, SAMPLE_TEMP_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_NOTICE  (Index) 
--
CREATE UNIQUE INDEX PK_NOTICE ON NOTICE
(NOTICE_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_MTLR_MST  (Index) 
--
CREATE UNIQUE INDEX PK_MTLR_MST ON MTLR_MST
(MTLR_MST_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- TEST_SAMPLE_ATTACH_PK  (Index) 
--
CREATE UNIQUE INDEX TEST_SAMPLE_ATTACH_PK ON TEST_SAMPLE_ATTACH
(ATT_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- USER_INFO_PK  (Index) 
--
CREATE UNIQUE INDEX USER_INFO_PK ON USER_INFO
(USER_ID)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- IDX01_INDV_SPEC  (Index) 
--
CREATE INDEX IDX01_INDV_SPEC ON INDV_SPEC
(TESTITM_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ZIP_ADDR_PK  (Index) 
--
CREATE UNIQUE INDEX ZIP_ADDR_PK ON ZIP_ADDR
(BUILDING_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_USER_LOG_HISTORY  (Index) 
--
CREATE UNIQUE INDEX PK_USER_LOG_HISTORY ON USER_LOG_HISTORY
(LOG_ID)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- REPORT_DOC_PK  (Index) 
--
CREATE UNIQUE INDEX REPORT_DOC_PK ON REPORT_DOC
(REPORT_DOC_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_INST_USE_HIS  (Index) 
--
CREATE UNIQUE INDEX PK_INST_USE_HIS ON INST_USE_HIS
(USE_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- EQUIPRENT_SAMPLE_PK  (Index) 
--
CREATE UNIQUE INDEX EQUIPRENT_SAMPLE_PK ON INST_RENT_SAMPLE
(INSTRENT_RENT_NO, INSTRENT_SAMPLE_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_TEST_STD_REV  (Index) 
--
CREATE UNIQUE INDEX PK_TEST_STD_REV ON TEST_STD_REV
(REV_NO, TEST_STD_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_TEST_STD  (Index) 
--
CREATE UNIQUE INDEX PK_TEST_STD ON TEST_STD
(TEST_STD_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- DOC_ATTACH_PK  (Index) 
--
CREATE UNIQUE INDEX DOC_ATTACH_PK ON DOC_ATTACH
(DOC_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- DOCUMENT_PK  (Index) 
--
CREATE UNIQUE INDEX DOCUMENT_PK ON DOCUMENT
(DOC_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- DEPT_TEAM_USER_PK  (Index) 
--
CREATE UNIQUE INDEX DEPT_TEAM_USER_PK ON DEPT_TEAM_USER
(TEAM_CD, USER_ID)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- DEPT_TEAM_PK  (Index) 
--
CREATE UNIQUE INDEX DEPT_TEAM_PK ON DEPT_TEAM
(DEPT_CD, TEAM_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_EDU_RESULT_DOC  (Index) 
--
CREATE UNIQUE INDEX PK_EDU_RESULT_DOC ON EDU_RESULT_DOC
(EDU_DOC_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_TEST_SAMPLE_ITEM  (Index) 
--
CREATE UNIQUE INDEX PK_TEST_SAMPLE_ITEM ON TEST_SAMPLE_ITEM
(TEST_SAMPLE_SEQ, TEST_ITEM_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_TEST_SAMPLE  (Index) 
--
CREATE UNIQUE INDEX PK_TEST_SAMPLE ON TEST_SAMPLE
(TEST_SAMPLE_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- SAMPLE_HISTORY_PK  (Index) 
--
CREATE UNIQUE INDEX SAMPLE_HISTORY_PK ON SAMPLE_HISTORY
(TEST_SAMPLE_SEQ, SAMPLE_HIS_SEQ)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          384K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- IDX_SAMPLEING_POINT  (Index) 
--
CREATE INDEX IDX_SAMPLEING_POINT ON SAMPLING_POINT
(WATER_SYSTEM, SAMPLING_OBJECT)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- IDX02_INDV_SPEC  (Index) 
--
CREATE INDEX IDX02_INDV_SPEC ON INDV_SPEC
(PRDLST_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- INSTRUMENT_PK  (Index) 
--
CREATE UNIQUE INDEX INSTRUMENT_PK ON INSTRUMENT
(INST_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_DEPT_UNIT_WORK  (Index) 
--
CREATE UNIQUE INDEX PK_DEPT_UNIT_WORK ON DEPT_UNIT_WORK
(UNIT_WORK_CD, DEPT_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- EQUIPRENT_EQUIP_PK  (Index) 
--
CREATE UNIQUE INDEX EQUIPRENT_EQUIP_PK ON INST_RENT_INST
(INSTRENT_RECEIPT_NO, INSTRENT_RENT_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- ESTIMATE_DETAIL_PK  (Index) 
--
CREATE UNIQUE INDEX ESTIMATE_DETAIL_PK ON ESTIMATE_ITEM
(EST_ITEM_NO, EST_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- EQUIPRENT_ITEM_PK  (Index) 
--
CREATE UNIQUE INDEX EQUIPRENT_ITEM_PK ON INST_RENT_ITEM
(INSTRENT_SAMPLE_NO, TEST_ITEM_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- MTLR_INFO_PK  (Index) 
--
CREATE UNIQUE INDEX MTLR_INFO_PK ON MTLR_INFO
(MTLR_NO)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



--
-- PK_UNIT_WORK  (Index) 
--
CREATE UNIQUE INDEX PK_UNIT_WORK ON UNIT_WORK
(UNIT_WORK_CD)
LOGGING
TABLESPACE LIMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


