DROP USER LIMS CASCADE;

CREATE USER LIMS
  IDENTIFIED BY VALUES 'LIMSDB'
  DEFAULT TABLESPACE LIMS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for LIMS 
  GRANT EXP_FULL_DATABASE TO LIMS WITH ADMIN OPTION;
  GRANT DBA TO LIMS;
  ALTER USER LIMS DEFAULT ROLE DBA;
  -- 1 System Privilege for LIMS 
  GRANT UNLIMITED TABLESPACE TO LIMS;



DROP USER RDMS CASCADE;

CREATE USER RDMS
  IDENTIFIED BY VALUES 'MANAGER'
  DEFAULT TABLESPACE RDMS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for RDMS 
  GRANT RESOURCE TO RDMS;
  GRANT CONNECT TO RDMS;
  GRANT DBA TO RDMS;
  ALTER USER RDMS DEFAULT ROLE ALL;
  -- 4 System Privileges for RDMS 
  GRANT UNLIMITED TABLESPACE TO RDMS;
  GRANT CREATE VIEW TO RDMS;
  GRANT CREATE PROCEDURE TO RDMS;
  GRANT CREATE SEQUENCE TO RDMS;
  -- 6 Object Privileges for RDMS 
    GRANT SELECT ON HDLIMS.DEPART TO RDMS;
    GRANT SELECT ON HDLIMS.USER_INFO TO RDMS;
    GRANT SELECT ON KBLIMS.DEPART TO RDMS;
    GRANT SELECT ON KBLIMS.USER_INFO TO RDMS;
    GRANT SELECT ON LIMS.DEPART TO RDMS;
    GRANT SELECT ON LIMS.USER_INFO TO RDMS;


